.PHONY:test correct clean all

all: 
	go run main.go avl.go common.go test.go correct.go

test:
	go run main.go avl.go common.go test.go correct.go -test

correct:
	go run main.go avl.go common.go test.go correct.go -correct